-- | Writes the per-package @BUCK.cabal.bzl@\/@BUCK@ files for every local
-- project package.
--
-- Two files, not one, per package directory:
--
--   * @BUCK.cabal.bzl@ is fully regenerated on every run (it's marked
--     @\@generated@ and never hand-edited) and defines a single
--     @generated_targets()@ macro with one rule call per buildable
--     component.
--   * @BUCK@ is created only if it doesn't already exist, as a two-line
--     file that loads and calls that macro. This is the file a user is
--     free to hand-edit - to add extra targets, or stop calling
--     @generated_targets()@ altogether for a package that needs fully
--     custom rules - without a re-run of @cabal buck2@ ever touching it.
module Distribution.Client.Buck2.Generate
  ( generateAllPackages
  ) where

import Distribution.Client.Compat.Prelude
import Prelude ()

import System.Directory (doesFileExist)
import System.FilePath (makeRelative, (</>))

import qualified Data.Map as Map

import Distribution.Package (packageName)
import Distribution.PackageDescription (PackageDescription)
import Distribution.Pretty (prettyShow)
import Distribution.Types.PackageName (PackageName)

import Distribution.Simple.Utils (notice, warn)
import Distribution.Verbosity (Verbosity)

import Distribution.Client.Buck2.CabalToBuck
import Distribution.Client.Buck2.Starlark

-- | Generate\/refresh @BUCK.cabal.bzl@ (and @BUCK@, where missing) for
-- every local package. @projectRoot@ is the buck2 cell root (the
-- directory containing @.buckconfig@), used to turn each package's
-- absolute directory into the cell-relative one buck2 target labels need.
generateAllPackages :: Verbosity -> FilePath -> [(FilePath, PackageDescription)] -> IO ()
generateAllPackages verbosity projectRoot pkgs = do
  traverse_ (generateOnePackage verbosity localIndex projectRoot) pkgs
  where
    localIndex :: LocalPackageIndex
    localIndex =
      Map.fromList
        [ (packageName pkgDesc, rootRelativeDir projectRoot pkgDir)
        | (pkgDir, pkgDesc) <- pkgs
        ]

rootRelativeDir :: FilePath -> FilePath -> FilePath
rootRelativeDir projectRoot pkgDir = case makeRelative projectRoot pkgDir of
  "" -> "."
  rel -> rel

generateOnePackage :: Verbosity -> LocalPackageIndex -> FilePath -> (FilePath, PackageDescription) -> IO ()
generateOnePackage verbosity localIndex projectRoot (pkgDir, pkgDesc) = do
  targets <- generatePackageTargets verbosity localIndex pkgDir pkgDesc
  let pkgName = packageName pkgDesc
  if null (ptCalls targets)
    then warn verbosity $ "cabal buck2: no buck2 targets generated for package " ++ show pkgName
    else do
      let bzlPath = pkgDir </> "BUCK.cabal.bzl"
          buckPath = pkgDir </> "BUCK"
      writeFile bzlPath (renderGeneratedBzl pkgName targets)
      buckExists <- doesFileExist buckPath
      unless buckExists $ writeFile buckPath renderBuckWrapper
      notice verbosity $
        "cabal buck2: generated "
          ++ (rootRelativeDir projectRoot pkgDir </> "BUCK.cabal.bzl")
          ++ " ("
          ++ show (length (ptCalls targets))
          ++ " target(s))"
          ++ (if buckExists then "" else ", created " ++ (rootRelativeDir projectRoot pkgDir </> "BUCK"))

renderGeneratedBzl :: PackageName -> PackageTargets -> String
renderGeneratedBzl pkgName targets =
  unlines
    [ "# @generated by `cabal buck2` from " ++ prettyShow pkgName ++ ".cabal - do not edit by hand."
    , "# Re-run `cabal buck2` after editing the .cabal file to refresh this file."
    ]
    ++ "\n"
    ++ concatMap (uncurry renderLoad) (ptLoads targets)
    ++ "\n"
    ++ "def generated_targets():\n"
    ++ indentBlock (intercalate "\n" (map renderCall (ptCalls targets)))

indentBlock :: String -> String
indentBlock = unlines . map indentLine . lines
  where
    indentLine "" = ""
    indentLine l = "    " ++ l

renderBuckWrapper :: String
renderBuckWrapper =
  unlines
    [ "# Hand-maintained: add extra targets below, or stop calling"
    , "# generated_targets() to fully take over this package's BUCK rules."
    , "load(\":BUCK.cabal.bzl\", \"generated_targets\")"
    , ""
    , "generated_targets()"
    ]
